- name: Preflight check
  ansible.builtin.import_tasks: preflight-check.yml

- name: Install Jenkins
  ansible.builtin.import_tasks: setup-jenkins.yml

- name: Final Check
  ansible.builtin.import_tasks: final-check.yml
