---
- name: restart jenkins
  become: true
  ansible.builtin.systemd:
    name: jenkins
    state: restarted
    daemon_reload: true
  listen: restart jenkins

- name: wait for jenkins
  ansible.builtin.uri:
    url: "{{ jenkins_url }}/login"
    method: GET
    status_code: [200, 403]
    timeout: 10
  register: result
  until: result.status in [200, 403]
  retries: 60
  delay: 5
  listen: restart jenkins
